name: Static Analysis

on:
  push:
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Format
        run: terraform fmt -check
